# Generated by Django 2.1.4 on 2018-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_info', '0005_auto_20181208_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgoal',
            name='payment_goal',
            field=models.TextField(max_length=50, null=True, verbose_name='Payment Goal Name'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='payment_info',
            field=models.TextField(max_length=50, null=True, verbose_name='Name of Loan'),
        ),
    ]
