# Generated by Django 2.1.4 on 2018-12-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=50)),
                ('loan_intrest_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('loan_payment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('loan_current_balance', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
