# Generated by Django 2.1.4 on 2018-12-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_info', '0004_auto_20181213_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='loan_intrest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
