# Generated by Django 2.1.4 on 2018-12-17 00:13

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loan_info', '0007_auto_20181216_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandetail',
            old_name='intrest_monthly_currency',
            new_name='interest_monthly_currency',
        ),
        migrations.RenameField(
            model_name='loandetail',
            old_name='loan_intrest_rate',
            new_name='loan_interest_rate',
        ),
        migrations.RemoveField(
            model_name='loandetail',
            name='intrest_monthly',
        ),
        migrations.AddField(
            model_name='loandetail',
            name='interest_monthly',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=10, verbose_name='Monthly Interest'),
        ),
    ]
